language: python
python: 2.7
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py27-pyopenssl013
    # Fails with '.../OpenSSL/SSL.so: undefined symbol: SSLv2_method'.
    # - TOX_ENV=py27-pyopenssl012
    - TOX_ENV=py33
    - TOX_ENV=py34
    - TOX_ENV=pypy
    - TOX_ENV=flake8
    - TOX_ENV=py3flake8

install:
    - pip install tox coveralls

script:
    - tox --hashseed 0 -e $TOX_ENV

after_success:
    - coveralls
