dist: xenial
group: travis_latest
sudo: false
cache:
  directories:
    - $HOME/.cache/pip

language: python


matrix:
  fast_finish: true

  include:
    # lint
    - python: "3.7"
      stage: lint
      env: TOXENV=lint
    - python: "3.7"
      env: TOXENV=manifest

    # test
    - python: "2.7"
      stage: test
      env: TOXENV=py27
    - python: "3.7"
      env: TOXENV=py37
    - python: "2.7"
      env: TOXENV=py27-pyopenssl014-idna
    - python: "2.7"
      env: TOXENV=py27-pyopensslLatest-idna
    - python: "2.7"
      env: TOXENV=py27-pyopensslLatest-noidna
    - python: "3.4"
      env: TOXENV=py34-pyopenssl014-idna
    - python: "3.4"
      env: TOXENV=py34-pyopensslLatest-idna
    - python: "3.5"
      env: TOXENV=py35-pyopenssl014-idna
    - python: "3.5"
      env: TOXENV=py35-pyopensslLatest-idna
    - python: "3.6"
      env: TOXENV=py36-pyopenssl014-idna
    - python: "3.6"
      env: TOXENV=py36-pyopensslLatest-idna
    - python: "3.6"
      env: TOXENV=py36-pyopensslLatest-noidna
    - python: "3.7"
      env: TOXENV=py37-pyopenssl014-idna
    - python: "3.7"
      env: TOXENV=py37-pyopensslLatest-idna
    - python: "3.7"
      env: TOXENV=py37-pyopensslLatest-noidna
    - python: "pypy"
      dist: trusty
      env: TOXENV=pypy
    - python: "pypy3"
      dist: trusty
      env: TOXENV=pypy3
    - python: "pypy"
      dist: trusty
      env: TOXENV=pypy-pyopensslLatest-idna
    - python: "pypy3"
      dist: trusty
      env: TOXENV=pypy3-pyopensslLatest-idna

    # Prevent breakage by a new releases
    - python: "3.6-dev"
      env: TOXENV=py36-pyopensslLatest-idna
    - python: "3.7-dev"
      env: TOXENV=py37-pyopensslLatest-idna

    # Docs
    - python: "3.7"
      stage: docs
      env: TOXENV=docs
    - python: "3.7"
      env: TOXENV=pypi-description

  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"


install:
  - pip install -U tox


script:
  - tox


before_install:
  - pip install codecov


after_success:
  - tox -e coverage-report
  - codecov


notifications:
  email: false
